### ISSUE TITLE
OAuthPermissionsException-This request requires scope=likes

### ISSUE THREAD

**Issue by alejoar** [cyandterry/Like-My-GF#2]
I'm getting this error:

```
$ python like_my_gf.py 
Traceback (most recent call last):
  File "like_my_gf.py", line 82, in <module>
    liked_media = auth_request()
  File "like_my_gf.py", line 72, in auth_request
    api.like_media(media.id)
  File "/home/a/alejoar/local/lib/python2.7/site-packages/python_instagram-1.3.2-py2.7.egg/instagram/bind.py", line 197, in _call
    return method.execute()
  File "/home/a/alejoar/local/lib/python2.7/site-packages/python_instagram-1.3.2-py2.7.egg/instagram/bind.py", line 189, in execute
    content, next = self._do_api_request(url, method, body, headers)
  File "/home/a/alejoar/local/lib/python2.7/site-packages/python_instagram-1.3.2-py2.7.egg/instagram/bind.py", line 163, in _do_api_request
    raise InstagramAPIError(status_code, content_obj['meta']['error_type'], content_obj['meta']['error_message'])
instagram.bind.InstagramAPIError: (400) OAuthPermissionsException-This request requires scope=likes, but this access token is not authorized with this scope. The user must re-authorize your application with scope=likes to be granted write permissions.
```

Already got my access code.

**Comment by Zensavona** [comment]
It's because to like media with IG's API, you need special permission which is near impossible to get.

**Comment by petey9891** [comment]
I'm having the same error, how do I fix it?
